#ifndef _STATE_CODE_H_
#define _STATE_CODE_H_
typedef enum {
		CHECK_VALIDITY = 0,
		CHECK_SIGNATURE = 1,
		SOS_COPIED = 2,
		RESOURCE_COPIED = 3,
		CREATE_OPTIMIZEDDIR = 4,
		DEPENDENCY_CHECKED = 5,
		CONTENTS_DOWNLOAD_READY = 6,
   		CONTENTS_DOWNLOAD_PROGRESS =7
}StateCode;
#endif